# Generated by Django 4.1.7 on 2023-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('NEBULA', 'Nebula'), ('STAR', 'Star'), ('GALAXY', 'Galaxy'), ('PLANET', 'Planea')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
